### ISSUE TITLE
[Epic]: Draft of the CIP

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/CIP-High-Assurance#2]
### Acknowledgements

- [X] I am a member of the team

### Epic description

Draft of the actual CIP. 

### Acceptance Criteria/Task List

- [x] #10
- [x] #11
- [x] Fill the CIP template
    - [x] #12
    - [x] #13
    - [x] #14
    - [x] #15
    - [x] #21
    - [x] #17
    - [x] #16
        - [x] #18
        - [x] #19
    - [x] #20

### Extended goals
- [ ] Presentation at a CIP editor meeting
- [x] Presentation at a Certification and/or High Assurance Working Group
- [ ] CIP in Draft

### Priority

High

**Comment by RSoulatIOHK** [comment]
This is the CIP draft: https://docs.google.com/document/d/1nxY-bOIrTYK2_jczA8iCL8RWGLDa1M5jez6v0zN6lUM/edit
